#!/bin/bash

# Verifica que se pase el número de iteraciones
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <numero_de_iteraciones>"
    exit 1
fi

ITERATIONS=$1

./pa $ITERATIONS &

gnome-terminal -- ./pb $ITERATIONS & 

gnome-terminal -- ./pc $ITERATIONS &

